version: 2
updates:
  - package-ecosystem: "bun"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    ignore:
      - dependency-name: "zod"
        versions: [ "4" ]
    directories:
      - "/"
      - "/frontend"
      - "/backend"