name: release automation

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: set up bun
        uses: oven-sh/setup-bun@v1

      - name: install deps
        run: bun install

      - name: run tests
        run: bun test

      - name: run semantic release
        run: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
