name: tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-backend:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: set up bun
        uses: oven-sh/setup-bun@v1

      - name: install deps and run tests in /backend
        run: cd backend && bun install && bun test
        env:
          JWT_SECRET: "03701e1b4550c20fa380692f385f34279e2415ad5906b2e9ca02893118299646"